evispa_resource_manager:
    resource: "@EvispaResourceManagerBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

evispa_product_resource:
    type: rest
    resource: "@EvispaProductApiBundle/Resources/config/products_routes.xml"
    prefix:   /admin


