NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

evispa_product_admin:
    type: rest
    resource: "@EvispaProductAdminBundle/Resources/config/products_routes.xml"
    prefix:   /admin


